[2024-08-28T09:15:03.170+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-28T09:15:03.194+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator.insert_into_table scheduled__2024-08-26T00:00:00+00:00 [queued]>
[2024-08-28T09:15:03.206+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator.insert_into_table scheduled__2024-08-26T00:00:00+00:00 [queued]>
[2024-08-28T09:15:03.207+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 6
[2024-08-28T09:15:03.227+0000] {taskinstance.py:2879} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-08-26 00:00:00+00:00
[2024-08-28T09:15:03.244+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1317) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-28T09:15:03.245+0000] {standard_task_runner.py:72} INFO - Started process 1328 to run task
[2024-08-28T09:15:03.246+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator', 'insert_into_table', 'scheduled__2024-08-26T00:00:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/postgres-demo.py', '--cfg-path', '/tmp/tmpzhjmdf3u']
[2024-08-28T09:15:03.248+0000] {standard_task_runner.py:105} INFO - Job 76: Subtask insert_into_table
[2024-08-28T09:15:03.320+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator.insert_into_table scheduled__2024-08-26T00:00:00+00:00 [running]> on host 2d2e6ae1efc8
[2024-08-28T09:15:03.437+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='asukhikh' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-08-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-26T00:00:00+00:00'
[2024-08-28T09:15:03.439+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-28T09:15:03.440+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-28T09:15:03.440+0000] {logging_mixin.py:190} INFO - Current task name:insert_into_table state:running start_date:2024-08-28 09:15:03.195388+00:00
[2024-08-28T09:15:03.441+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator and current dag run status:running
[2024-08-28T09:15:03.442+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-28T09:15:03.443+0000] {sql.py:282} INFO - Executing: 
            INSERT INTO Orders
            SELECT 
                floor(random() * 10) as OrderID,
                (array['created', 'in transit', 'delivered'])[floor(random() * 3 + 1) as Status
            FROM generate_series(1, 1)
        
[2024-08-28T09:15:03.459+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2024-08-28T09:15:03.482+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2024-08-28T09:15:03.631+0000] {sql.py:509} INFO - Running statement: 
            INSERT INTO Orders
            SELECT 
                floor(random() * 10) as OrderID,
                (array['created', 'in transit', 'delivered'])[floor(random() * 3 + 1) as Status
            FROM generate_series(1, 1)
        , parameters: None
[2024-08-28T09:15:03.639+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "as"
LINE 5: ...in transit', 'delivered'])[floor(random() * 3 + 1) as Status
                                                              ^

[2024-08-28T09:15:03.674+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-08-28T09:15:03.675+0000] {logging_mixin.py:190} INFO - Task start:2024-08-28 09:15:03.195388+00:00 end:2024-08-28 09:15:03.672617+00:00 duration:0.477229
[2024-08-28T09:15:03.675+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): insert_into_table> dag:<DAG: dag_with_postgres_operator> dagrun:<DagRun dag_with_postgres_operator @ 2024-08-26 00:00:00+00:00: scheduled__2024-08-26T00:00:00+00:00, state:running, queued_at: 2024-08-28 09:11:22.301446+00:00. externally triggered: False>
[2024-08-28T09:15:03.676+0000] {logging_mixin.py:190} INFO - Failure caused by syntax error at or near "as"
LINE 5: ...in transit', 'delivered'])[floor(random() * 3 + 1) as Status
                                                              ^
[2024-08-28T09:15:03.677+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator, task_id=insert_into_table, run_id=scheduled__2024-08-26T00:00:00+00:00, execution_date=20240826T000000, start_date=20240828T091503, end_date=20240828T091503
[2024-08-28T09:15:03.713+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-28T09:15:03.715+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 76 for task insert_into_table (syntax error at or near "as"
LINE 5: ...in transit', 'delivered'])[floor(random() * 3 + 1) as Status
                                                              ^
; 1328)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "as"
LINE 5: ...in transit', 'delivered'])[floor(random() * 3 + 1) as Status
                                                              ^

[2024-08-28T09:15:03.784+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-28T09:15:03.798+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-08-28T09:15:03.821+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-28T09:15:03.826+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2024-08-28T09:23:51.358+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-28T09:23:51.392+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator.insert_into_table scheduled__2024-08-26T00:00:00+00:00 [queued]>
[2024-08-28T09:23:51.405+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator.insert_into_table scheduled__2024-08-26T00:00:00+00:00 [queued]>
[2024-08-28T09:23:51.406+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 6
[2024-08-28T09:23:51.428+0000] {taskinstance.py:2879} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-08-26 00:00:00+00:00
[2024-08-28T09:23:51.446+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1486) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-28T09:23:51.449+0000] {standard_task_runner.py:72} INFO - Started process 1488 to run task
[2024-08-28T09:23:51.449+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator', 'insert_into_table', 'scheduled__2024-08-26T00:00:00+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/postgres-demo.py', '--cfg-path', '/tmp/tmp8xs4nla2']
[2024-08-28T09:23:51.451+0000] {standard_task_runner.py:105} INFO - Job 95: Subtask insert_into_table
[2024-08-28T09:23:51.539+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator.insert_into_table scheduled__2024-08-26T00:00:00+00:00 [running]> on host 2d2e6ae1efc8
[2024-08-28T09:23:51.651+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='asukhikh' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-08-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-26T00:00:00+00:00'
[2024-08-28T09:23:51.653+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-28T09:23:51.654+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-28T09:23:51.654+0000] {logging_mixin.py:190} INFO - Current task name:insert_into_table state:running start_date:2024-08-28 09:23:51.393831+00:00
[2024-08-28T09:23:51.655+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator and current dag run status:running
[2024-08-28T09:23:51.655+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-28T09:23:51.656+0000] {sql.py:282} INFO - Executing: 
            INSERT INTO Orders
            SELECT 
                floor(random() * 10) as OrderID,
                (array['created', 'in transit', 'delivered'])[floor(random() * 3 + 1)] as Status
            FROM generate_series(1, 1)
        
[2024-08-28T09:23:51.674+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2024-08-28T09:23:51.698+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2024-08-28T09:23:51.903+0000] {sql.py:509} INFO - Running statement: 
            INSERT INTO Orders
            SELECT 
                floor(random() * 10) as OrderID,
                (array['created', 'in transit', 'delivered'])[floor(random() * 3 + 1)] as Status
            FROM generate_series(1, 1)
        , parameters: None
[2024-08-28T09:23:51.915+0000] {sql.py:518} INFO - Rows affected: 1
[2024-08-28T09:23:51.936+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-28T09:23:51.937+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator, task_id=insert_into_table, run_id=scheduled__2024-08-26T00:00:00+00:00, execution_date=20240826T000000, start_date=20240828T092351, end_date=20240828T092351
[2024-08-28T09:23:51.967+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-08-28T09:23:51.968+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-08-28T09:23:51.968+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator queued_at:2024-08-28 09:21:07.630512+00:00
[2024-08-28T09:23:51.969+0000] {logging_mixin.py:190} INFO - Task hostname:2d2e6ae1efc8 operator:PostgresOperator
[2024-08-28T09:23:51.989+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-28T09:23:52.008+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-08-28T09:23:52.023+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-28T09:23:52.027+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2024-08-28T09:28:40.232+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-28T09:28:40.250+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator.insert_into_table scheduled__2024-08-26T00:00:00+00:00 [queued]>
[2024-08-28T09:28:40.257+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator.insert_into_table scheduled__2024-08-26T00:00:00+00:00 [queued]>
[2024-08-28T09:28:40.258+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 6
[2024-08-28T09:28:40.271+0000] {taskinstance.py:2879} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-08-26 00:00:00+00:00
[2024-08-28T09:28:40.278+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1547) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-28T09:28:40.279+0000] {standard_task_runner.py:72} INFO - Started process 1549 to run task
[2024-08-28T09:28:40.279+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator', 'insert_into_table', 'scheduled__2024-08-26T00:00:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/postgres-demo.py', '--cfg-path', '/tmp/tmpvqei1ydp']
[2024-08-28T09:28:40.280+0000] {standard_task_runner.py:105} INFO - Job 100: Subtask insert_into_table
[2024-08-28T09:28:40.323+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator.insert_into_table scheduled__2024-08-26T00:00:00+00:00 [running]> on host 2d2e6ae1efc8
[2024-08-28T09:28:40.393+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='asukhikh' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-08-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-26T00:00:00+00:00'
[2024-08-28T09:28:40.394+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-28T09:28:40.395+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-28T09:28:40.395+0000] {logging_mixin.py:190} INFO - Current task name:insert_into_table state:running start_date:2024-08-28 09:28:40.250865+00:00
[2024-08-28T09:28:40.395+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator and current dag run status:running
[2024-08-28T09:28:40.396+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-28T09:28:40.396+0000] {sql.py:282} INFO - Executing: 
            INSERT INTO orders
            SELECT 
                floor(random() * 1000000) as order_id,
                (array['created', 'in transit', 'delivered'])[floor(random() * 3 + 1)] as status
            FROM generate_series(1, 1);
        
[2024-08-28T09:28:40.405+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2024-08-28T09:28:40.415+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2024-08-28T09:28:40.481+0000] {sql.py:509} INFO - Running statement: 
            INSERT INTO orders
            SELECT 
                floor(random() * 1000000) as order_id,
                (array['created', 'in transit', 'delivered'])[floor(random() * 3 + 1)] as status
            FROM generate_series(1, 1);
        , parameters: None
[2024-08-28T09:28:40.487+0000] {sql.py:518} INFO - Rows affected: 1
[2024-08-28T09:28:40.499+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-28T09:28:40.500+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator, task_id=insert_into_table, run_id=scheduled__2024-08-26T00:00:00+00:00, execution_date=20240826T000000, start_date=20240828T092840, end_date=20240828T092840
[2024-08-28T09:28:40.510+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-08-28T09:28:40.511+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-08-28T09:28:40.511+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator queued_at:2024-08-28 09:26:46.053615+00:00
[2024-08-28T09:28:40.512+0000] {logging_mixin.py:190} INFO - Task hostname:2d2e6ae1efc8 operator:PostgresOperator
[2024-08-28T09:28:40.534+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-28T09:28:40.544+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-08-28T09:28:40.552+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-28T09:28:40.555+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
